### ISSUE TITLE
Sentence

### ISSUE THREAD

**Issue by Truyn** [Stewart-Anubis/Zr-Leader2-Anubis-Edition#1]
1)Add auto voting every round. (If there is no administrator on the server)
2)Leader illumination (through the walls for people)
3)Slightly expand leader management through the admin

**Comment by Stewart-Anubis** [comment]
Test - https://github.com/Stewart-Anubis/Zr-Leader-Ultimate

**Comment by Truyn** [comment]
Good.
everything seems to be working so far

Now auto-vote if there is no admin

**Comment by Truyn** [comment]
and cvar disable plugin. i use zm/ze maps

**Comment by Stewart-Anubis** [comment]
Added cvar to disable plugin. Update - https://github.com/Stewart-Anubis/Zr-Leader-Ultimate
When I have more time, I'll see the other requests.
Thanks!

**Comment by Truyn** [comment]
Thanks you!
