### ISSUE TITLE
Leader mute function bugged the sourcebans mute record

### ISSUE THREAD

**Issue by Oz-Lin** [Stewart-Anubis/Zr-Leader2-Anubis-Edition#2]
When the leader enables mute, and other players tried to use voice chat, it goes to the sourcebans' comm blocks.

Is this an intended feature by using BaseComm natives? Cheers

**Comment by Stewart-Anubis** [comment]
It uses the native feature of "BaseComm" "BaseComm_SetClientMute(client, true);" , but in the new version "SetClientListeningFlags(client, VOICE_MUTED);" . Use the new version.
New version ;
https://github.com/Stewart-Anubis/Zr-Leader-Ultimate
